### ISSUE TITLE
Year and copyright holder not filled out

### ISSUE THREAD

**Issue by mistergaskill** [collectivehealth/unity#3]
https://github.com/collectivehealth/unity/blob/6ec1f7c1cc8a5ad62b2b6d9e93e79762c37d774c/LICENSE#L190

**Comment by darkobits** [comment]
These appear to be instructions from Apache to a potential reader of the license on how to use the license in their own work, and are therefore correct as-is.

**Comment by mistergaskill** [comment]
whoops, read too quickly - sorry about that. thanks for checking
